### PR TITLE
Adding past exam solutions

### PR DESCRIPTION
**Pull request by lchipchase**
Should we add past exam solutions, I have finished the 2018 past paper, but if we were able to get a question bank for solutions on past papers this would be good no? I haven't added any actual links yet, but just a suggestion if people want to contribute their answers

### CODE REVIEW

**Comment by jfitz02** [comment]
I have a few uncompleted past papers
Can open my overleaf documents for them for others to look at

**Comment by lchipchase** [comment]
Sweet, I can give the 2018 PDF now, I (think) its correct

**Comment by EdmundGoodman** [comment]
I **think** we're not allowed to, since the university owns the exam papers, and tells us not to distribute them, and by giving answers, you kind of implicitly state the questions

**Comment by EdmundGoodman** [comment]
@all-contributors please add @lchipchase for admin

**Pull request closed without merging**
